EducationalTestingService/skll

doc/run_experiment.rst
==============================================================
The section explaining the -a/--ablation flag contained some incorrect information. Specifically, no mention was made of ablation experiments also including a run with all features as a baseline.
=> Modified  section of tutorial.

conda.yaml, skll/version.py
This is a fairly minor bugfix release.  Changes include:
-  Update links in README.
-  Fix crash when trying to run experiments with integer labels (Issue #225, PR #219)
-  Update documentation about ablation to note that there will always be a run with all features (Issue #224, PR #226)
-  Update documentation about format of `cv_folds_file` (Issue #225, PR #228)
-  Remove duplicate words in documentation (PR #218)
-  Fixed `KeyError` when trying to build conda recipe.
-  Update outdated parameter grids in `run_experiment` documentation (commit 80d78e4)
=> Release 1.0.1

.travis.yml, doc/run_experiment.rst, requirements_rtd.txt, skll/experiments.py, tests/test_input.py, tests/test_output.py
This PR addresses #222 and #160. 
New options available in config file: 
``cv_folds``: specify the number of folds for cross validation
``random_folds``: when set to True, does not do stratified cross-validation
Added documentation for above options. 
Added missing documentation for ``grid_search_folds``. 
Fixed an apparent bug in ``experiments.py`` where the value of ``grid_search_folds`` set in the config file was being overwritten as 3 for model training when the task was not cross validation.
=> Expose cv_folds and stratified

.travis.yml, doc/run_experiment.rst, requirements.txt, requirements_rtd.txt, skll/learner.py, tests/test_classification.py, tests/test_metrics.py, tests/test_preprocessing.py, tests/test_regression.py
- Update `scikit-learn` to version 0.16.1 in `.travis.yml`, `requirements.txt`, and `requirements_rtd.txt`.
- Remove SVR coefficient correction now that the original bug has been fixed in scikit-learn (#111).
- Remove dependency on `BaseLibLinear` in `model_params()` since it is no longer exposed in scikit-learn (#233, #235).
- Expose `LinearSVR` from scikit-learn and so change `SVR` to *not* have a 'linear' kernel by default.
- Include `RescaledLinearSVR` among the rescaled regressors.
- Remove `SVR` from `test_linear_models()` in `test_regression.py` and create a new `test_non_linear_models()`.
- Update one of the expected values in `test_sparse_predict_sampler()` likely due to the following item in the scikit-learn 0.16 release notes: *"RBFSampler with gamma=g formerly approximated …
=> Compatibility with scikit-learn v0.16.1

doc/run_experiment.rst, skll/experiments.py, skll/learner.py, tests/test_classification.py, tests/test_regression.py, tests/utils.py
- Allow non-default base estimators for AdaBoost (#238)
- Correctly interpret the `base_estimator` fixed parameter for AdaBoostClassifiers and AdaBoostRegressors as objects instead of strings.
- Make sure that the base estimator for Adaboost has a fixed seed so that results are replicable.
- Add corresponding unit tests for both classification and regression and update documentation.
- Fix `hasher_features` typo in `experiments.py` (#234).
- Remove unnecessary setting of numpy global random seeds (#220)
- We are already passing in `random_state` seeds in `model_kwargs` for all classifiers/regressors so we don't need to set the `numpy` global random seed.
- Include `Lasso`, `ElasticNet`, `LinearSVR`, and `SVC` when setting the above seeds in `model_kwargs`.
- Remove requirements for …
=> Several minor bugfixes

skll/data/readers.py
Fix the division by zero error by adding one to the enumerator counter `ex_num`
=> correct total number of examples

skll/config.py
I got an email from a user about getting a `FileExistsError` when running the titanic example, and I noticed that we were checking to see if one path existed and then called `os.makedirs` to make a slightly different one existed.  This should fix that.
=> Fix issue where os.makedirs was being called for directories that already existed

skll/config.py
Otherwise the user might think that their feature hasher is being ignored. 
This fixes #265.
=> only print out a warning about hasher_features when feature_hasher is not set

.travis.yml
Since we cannot successfully get SGE to install on Travis CI and switching to another CI platform is too much work right now, we are going to disable 2/4 builds on Travis that use `gridmap`.
=> Remove `GRIDMAP=true` from .travis.yml

.travis.yml, conda.yaml, doc/run_experiment.rst, requirements.txt, requirements_rtd.txt, skll/learner.py, skll/utilities/generate_predictions.py, tests/other/majority_class_learner.py, tests/test_classification.py
The only change that was required was to patch up learner objects from older versions of SKLL (and scikit-learn) that we might load using the `from_file()` class method.
=> Update scikit-learn to 0.17.0

skll/data/featureset.py
Minor update to FeatureSet class documentation. Not sure whether it should go anywhere else.
=> added note about FeatureSet equality

examples/boston/cross_val.cfg, examples/boston/evaluate.cfg, skll/config.py, tests/configs/test_relative_paths.template.cfg, tests/test_input.py
Added in support of relative paths in config files for more than just the training/test set files (e.g. model directory, custom learner, etc.) + some unit tests.
=> Fix errors when using reusing relative paths in output section

.travis.yml
Currently, the `coveralls.io` build is broken because the `python-coveralls` in @dan-blanchard's channel is too old. I made a new package and put it in my `conda` channel and modified `.travis.yml` to use both @dan-blanchard's channel as well as my channel. This resurrects the `coveralls.io` builds as can be seen [here](https://coveralls.io/builds/5109277).
=> Get coveralls.io working

skll/config.py, tests/test_input.py
Added an extra check for empty config file name. This can generally only happen via the API.
=> Raise error when config file on command line is an empty string.

skll/learner.py, tests/test_regression.py
Currently the `fit()` method in the `rescaled()` decorator does not return `self` which is generally what `fit()` methods in `scikit-learn` should do. 
I fixed that and also modified the `test_rescaling()` regression test to also test rescaled learners without using grid search. So, we have new tests to check for this functionality which we didn't have before which is probably why this bug slipped through,
=> `fit()` in `rescaled()` decorator should return `self`

.travis.yml, requirements.txt, requirements_rtd.txt
While we were working on version 1.2 of SKLL, the `scikit-learn` folks released a [minor upgrade](http://scikit-learn.org/stable/whats_new.html) from 0.17.0 to 0.17.1. It most likely will not impact any of our tests but has some important bug fixes so we want to include it.
=> Upgrade scikit-learn to 0.17.1

conda-recipe/unix/skll/meta.yaml, conda-recipe/windows/skll/meta.yaml
The current conda recipe will not work. See #282. 
So, we need to have two separate recipes - one for Unix that does not use MKL and one for Windows where we have to use MKL.
=> Add new conda-recipes for unix and windows

.travis.yml, conda_requirements.txt, requirements.txt, requirements_rtd.txt, skll/__init__.py, skll/config.py, skll/experiments.py, skll/learner.py, tests/test_classification.py, tests/test_cv.py, tests/test_output.py, tests/test_preprocessing.py
- The major change in this version is that most the cross-validation and grid-search stuff has been moved to `sklearn.model_selection` AND the interface of the cross-validation generators has changed. They are no longer utterable directly but rather you have to initialize and then call the `.split()` method on them when you want the actual train/test indices.
- There are also some other major updates in the underlying algorithms themselves and in `make_classification()` which required changing the expected values in several of the tests. 
- I also address #231 by updating the F1-measure metrics in `metrics.py` and `__init__.py`.
- Finally, there are some minor changes like using `ruamel.yaml.safe_load()` instead of `ruamel.yaml.load()` since using the latter is no longer considered safe …
=> Upgrade scikit-learn to v0.18.1

.travis.yml, conda-recipe/skll/meta.yaml
- Remove and update dependencies in both `travis.yml` as well as the conda recipe (`logutils` does not seem to be used anywhere, `pyyaml` should be `ruamel.yaml`, and `beautiful-soup` has been renamed to `beautifulsoup4`)
- Switch to using `conda-forge` for some of the packages that are not in `defaults` instead of building them and saving them to the `desilinguist` channel.
=> Update to Python 3.6

doc/run_experiment.rst
Update documentation to say that:
- SVRs now use `rbf` kernels by default [issue #352].
- Add an inline note about CV fold computation when doing classification [issue #348].
- Add a footnote about `MPLBACKEND` when generating learning curves [issue #338].
=> Minor updates to documentation

.travis.yml, conda_requirements.txt, requirements.txt, requirements_rtd.txt, skll/learner.py
We only needed one very minor change to accommodate scikit-learn 0.19.1: which was that in  `learner.model_params`, we now call `reshape()` per sklearn's requirement on a 1D array before passing it to a method that expects a 2D array.
The rest of the changes are to the TravisCI config file and to the requirements files. I also tested the conda recipe with this version and it works fine though like with the python 3.6 switch, the change to the recipe will be pushed as part of the final release branch.
=> Update to scikit-learn v0.19.0

doc/run_experiment.rst, examples/make_boston_example_data.py, examples/make_iris_example_data.py, examples/make_titanic_example_data.py, skll/data/featureset.py, skll/data/readers.py
- Fix bug in `FeatureSet` iteration methods that would have failed if we were storing the feature values in non-sparse matrices (e.g., by setting `sparse=False` in `Reader` methods).
- Rename all data creation scripts to be consistent in their naming (`make_<name>_example_data.py`).
- Fix imports in those scripts to be consistent with scikit-learn v0.19.
- Fix indentation and remove unneeded imports.
=> Fix the example data creation scripts

doc/run_experiment.rst, skll/learner.py, tests/test_classification.py, tests/test_regression.py
1. Add the following new regressors:
- `BayesianRidge`
- `DummyRegressor`
- `HuberRegressors`
- `Lars`
- `MLPRegressor`
- `RANSACRegressor`
- `TheilSenRegressor`
2. Add the following new classifiers:
- `MLPClassifier`
- `RidgeClassifier`
3. Add default parameter grids where appropriate for these new learners. Blank default parameter grids for learners that do not have any hyper-parameters that make sense to tune by default and the decision is better left to the user.
4. Update documentation. 
- Add documentation for new learners.
- Fix incomplete documentation for previously existing learners.
- Add a note about empty default parameter grids.
5. Update tests. 
- Add tests for new learners.
- Refactor some old tests for consistency and ease of debugging.
=> Add new learners (mostly regressors)

skll/learner.py, tests/other/majority_class_learner.py
- We might have a situation where the default parameter grid for a learner is empty (this is the case for some new regressors that have been added as part of PR #377). In that case, if the user also doesn't provide a parameter grid to search but `grid_search` is `True`, there's no point actually doing the grid search and we should just use the default hyperparameters.
- This PR adds a warning to that effect and turns off grid search in this situation.
- It also changes some of the logging messages to actually use the readable learner name instead of the fully qualified class name.
- It fixes a bug with the custom learner used in the test which came up because there's no reason to do grid search for that majority class learner.
=> Do not do grid search if no param grids are provided

doc/run_experiment.rst, skll/__init__.py, skll/config.py, skll/data/readers.py, skll/data/writers.py, skll/experiments.py, skll/learner.py, skll/logutils.py, skll/metrics.py, skll/utilities/run_experiment.py, tests/configs/test_folds_file_grid.template.cfg, tests/test_cv.py
The goal of this PR is to improve how logging works in SKLL. The current situation is that many, if not all, of the warning messages are logged to the console but never stored in any of the log files. This is not great since a lot of people may not pay attention to the console messages. 
In an ideal situation, the solution would be quite simple. The way that `logging` works is that `logging.getLogger(<name>)` _always_ returns the same logger instance no matter where that call is made _as long as_ the call is within the same Python interpreter process. However, the problem is that SKLL jobs can also run on other machines in completely different Python processes. 
The solution in this PR works as follows:
1. I create a function called `get_skll_logger()` that returns a `Logger` instance …
=> Improve SKLL logging

README.rst, doc/run_experiment.rst, examples/titanic/evaluate_tuned.cfg, skll/config.py, skll/experiments.py, skll/learner.py, tests/configs/test_learning_curve.template.cfg, tests/configs/test_learning_curve_with_objectives.template.cfg, tests/configs/test_summary_feature_hasher_with_metrics.template.cfg, tests/configs/test_summary_with_metrics.template.cfg, tests/test_classification.py, tests/test_cv.py, tests/test_input.py, tests/test_output.py, tests/test_regression.py, tests/utils.py
Right now, the only metrics computed for any SKLL experiment are the tuning objectives. However, one may want to compute additional evaluation metrics without tuning on them. This PR makes that possible. 
- For `evaluate` and `cross_validate` tasks, one can now specify a `metrics` list in the Output section and those will be computed and saved at the end of the results file under an  "Additional Evaluation Metrics" section. For `train` and `predict` tasks, `metrics` is ignored since it's not relevant. 
- For `learning_curve` tasks, it doesn't actually make sense to have `objectives` anyway so you can specify `metrics` instead. Using `objectives` is still supported for backward compatibility but you will get a deprecation warning. (*Note*: as an implementation detail, we still use the …
=> Decouple evaluation metrics from tuning objectives

.travis.yml, tests/configs/test_ablation.template.cfg, tests/configs/test_ablation_all_combos.template.cfg, tests/configs/test_ablation_feature_hasher_all_combos.template.cfg, tests/configs/test_ablation_feature_hasher_sampler.template.cfg, tests/configs/test_ablation_feature_hasher_sampler_all_combos.template.cfg, tests/configs/test_ablation_sampler_all_combos.template.cfg, tests/test_ablation.py, tests/test_cv.py, tests/test_input.py, tests/test_output.py, tests/utils.py
Travis has a 50 minute hard limit on any job in any build and that includes VM boot up time. Now that we have so many tests, hitting that 50 minute job limit seems to be happening with more recent PRs. This PR breaks up the running of the test files into multiple jobs rather than running them all together. The solution implemented is detailed in #385.  
With this refactoring, the Travis CI plan runs for a total 26 minutes, taking into account the parallelization of the build jobs. And the longest running job is only ~20 min. See more details on [Travis CI](https://travis-ci.org/EducationalTestingService/skll).
This PR also solves some problems with `test_ablation.py`:
- Currently unless you run `test_ablation` first, some of the other tests will fail because they rely on a jsonlines file …
=> Refactor travis build

skll/experiments.py, tests/test_output.py
This is a very short PR.
- Fix return statement in `_classify_featureset()` such that running a learning curve task via `gridmap` actually works (see issue #386).
- Tweak how the y-limits for learning curves are computed so that we don't have a lot of wasted space (see issue #389). The curve below shows the new version of the curve that was attached in the issue.
- Update the y-limits test based on the tweak.
=> Fix learning curve gridmap bug and tweak y-limit computation.

.travis.yml, conda_requirements.txt, doc/run_experiment.rst, requirements.txt, requirements_rtd.txt, skll/config.py, skll/data/readers.py, skll/experiments.py, skll/learner.py, tests/test_classification.py, tests/test_featureset.py, tests/test_input.py
This is another short PR that encompasses several minor bugfixes and improvements:
1. Update to scikit-learn v0.19.1. In this particular scikit-learn release, the stratified split functions fail if the labels are floating point so we need to catch that condition in SKLL to provide a more informative message. Added such a condition to `learner.cross_validate()` and a test.
2. Deal with empty feature files by raising an exception. Added a test and also fixed an unbound variable bug.
3. Add `neg_log_loss` as a possible metric and tuning objective for classifiers. This requires `probability` to be `True` so add a check for that and a test.
4. If we are just specifying a `train_file` and a `test_file`, there are no featuresets and hence it doesn't make any sense to do ablation in that case. …
=> Multiple minor bug fixes and improvements

CONTRIBUTING.md, README.rst, doc/tutorial.rst
The `stable` branch of SKLL no longer serves any purpose since we now have packages and people who don't want to use `master` can just use the package for the last released version. 
- The public version of the documentation already points to `master`.
- In this PR, I remove all references to the `stable` branch.
I will delete the stable branch once this PR is merged.
=> Remove all references to the `stable` branch

skll/config.py
This is a tiny bug fix that moves the `Specifying "folds_file" overrides both explicit and default "num_cv_folds"` warning to make sure it only gets logged when "folds file" has been specified. The existing unit tests make sure this warning is triggered under the appropriate circumstances.
=> put folds_file warning in correct code block

skll/learner.py
- Change deletion of `logger` attribute from the Learner object to be conditional on whether it exists since older models will not have such an attribute.
=> Fix resaving of older models

skll/config.py, tests/test_input.py, tests/test_output.py
- We had a bug in the code where `_locate_file()` was being called and we were depending on its return value to decide whether to create the output directories or not. However `_locate_file()` raises an exception when the file doesn't already exist, so this was a total waste of time.
- I fixed the code so that we actually catch the exception for non-existent output directories and then use that to create the directories if needed. 
- For the tests, I simply removed the pre-test manual creation of the `output` directory from `test_output.py` such that the automatic directory creation will be tested.
=> Fix output directory creation

conda-recipe/skll/meta.yaml, skll/version.py
- All that was required was to change the version numbers.
- Conda and PyPI already updated.
- The release notes are already drafted and I will publish them once this PR is merged.
=> SKLL Release v1.5.1

skll/experiments.py, skll/learner.py, skll/utilities/generate_predictions.py, tests/configs/test_single_file_saved_subset.template.cfg, tests/test_classification.py, tests/test_utilities.py
- Create logger attribute via `from_file()` either created as a brand new one or passed in from the code calling `from_file()`.
-  Link the logger from `generate_predictions()` to the wrapper learner loaded via `from_file()`.
- Add a new test for `generate_predictions`. This test triggers a warning that should be printed using the Learner's logger that should exist even though the Learner was loaded using `from_file()` and not directly instantiated. This test uses a subset of features for evaluation since that will trigger a warning that forces the use of the logger. 
- Add a new test to `test_classification` that also uses a pre-trained model to evaluate on a subset  of the training features. 
@benbuleong please check using this branch to make sure that your experiment in #412 works …
=> Fix issue with missing loggers in Learner instances loaded via `from_file()`

skll/learner.py
- Remove `GradientBoostingClassifier` and `GradientBoostingRegressor` from list of learners that require dense matrices as input.
=> Allow gradient boosting models to take sparse matrices.

tests/test_classification.py, tests/test_regression.py
- Turn off grid search in MLP tests We need to do this since otherwise the travis builds time out. 
- This seems to be a problem on Linux machines (see #434).
- Turning off grid search is not ideal but it's not a terrible option.
=> Make MLP regression and classification tests run faster

.travis.yml, conda-recipe/skll/meta.yaml, conda_requirements.txt, requirements.txt, requirements_rtd.txt, skll/data/featureset.py, skll/experiments.py, skll/learner.py, tests/test_classification.py, tests/test_regression.py
- Update scikit-learn version in various requirement files.
- Update version in conda-recipe.
- Update version in `.travis.yaml`.
- Make minor changes to hyperparameters and parameter names necessitated by the version change.
- Update the expected values for a couple of tests - these are necessitated due to upstream changes and bug fixes in the MLP and Gradient Boosted models.
=> Update scikit-learn to v0.20.1

skll/data/writers.py, tests/test_featureset.py
The `_write_line()` method in `NDJWriter` assumes that we will always get numpy datatypes (e.g., `np.int64`) and hence uses `np.asscalar()` to convey them into scalar types before calling `json.dumps()` since numpy datatypes are not supported by JSON. However, this does not handle the edge case where a scalar datatype might show up, e.g., through the use of `pandas`. This PR fixes this and adds support for this edge case. It also adds new tests - based on the example shown in the related issue (#416). 
@bwriordan since you filed the issue, it'd be great if you can test this out. Thanks!
=> Fix NDJWriter bug

skll/learner.py, tests/test_utilities.py
For SVCs with linear kernels, we want to print out the primal weights - that is, the weights for each feature for each one-vs-one binary classifier. These are the weights contained in the `coef_` attribute of the underlying scikit-learn model. This is a matrix that has the shape [(n_classes)*(n_classes -1)/2, n_features] since there are C(n_classes, 2) = n_classes*(n_classes-1)/2 one-vs-one classifiers and each one has weights for each of the features. According to the [scikit-learn user guide](https://scikit-learn.org/stable/modules/svm.html#multi-class-classification) and the code for the function `_one_vs_one_coef()` in [`svm/base.py`](https://github.com/scikit-learn/scikit-learn/blob/55bf5d93e5674f13a1134d93a11fd0cd11aabcd1/sklearn/svm/base.py#L27), the order of the rows is as follows …
=> Make model parameters for SVCs with linear kernels accessible in SKLL

README.rst, conda-recipe/README.md, conda-recipe/skll/meta.yaml, doc/internal/release.rst, skll/version.py
- Update version numbers.
- Update links in README.
- Update release process documentation.
I have already built and uploaded the conda and PyPI packages and tested them locally on my Mac. They work fine. Feel free to test on other platforms 👍.
=> SKLL Release 1.5.3

skll/config.py, skll/experiments.py, skll/learner.py, tests/configs/test_int_labels_cv.template.cfg, tests/configs/test_single_file_saved_subset.template.cfg, tests/test_classification.py, tests/test_cv.py, tests/test_input.py, tests/test_metrics.py, tests/test_output.py, tests/test_regression.py
In order to be consistent with the API, it makes sense to set `grid_search` to be `True` by default in the config files. 
- Set default value of `grid_search` to be `True` in the config parser.
-  Update error message when no objectives are provided  to be more informative in light of this similar to the API error message.
- Move the grid search + learning curve check to config parsing instead of in `experiments.py` since it belongs here. And update the warning message to be more accurate.
- Update all tests and templates
- If we were not previously specifiying grid search, we wanted it to be false so we need to be explicit about that now.
- Explicitly specify grid search in API everywhere
- Fix some comments and docstrings in tests.
- Minor flake8 fixes.
=> Set default value of `grid_search` in config files to be `True`. 

skll/learner.py, skll/utilities/print_model_weights.py, tests/test_ablation.py, tests/test_regression.py, tests/test_utilities.py, tests/utils.py
- Modify `model_params` to work with hashed features. Since we lose the original feature names after hashing, we make up names in the format `hashed_feature_xx` in the output. 
- Tweak`print_model_weights` utility to print intercepts more clearly. For example, if the intercept list contains a single item, do not print it as a list.
- Update the utility function `make_regression_data()` to properly produce hashed feature data. This particular SKLL function relies on the sklearn function `make_regression()` which doesn’t know anything about hashed features. `make_regression()` works by generating random feature values, adding noise to them, generating weights randomly, and then computing the labels by taking dot product of the feature values and the weights. `make_regression_data()` then …
=> Make `model_params` and `print_model_weights` work with hashed features

doc/run_experiment.rst, skll/data/readers.py
I'm a bit unsure where this documentation should go. It would seem to be out of place and obtrusive almost anywhere except for in the `skll.readers` module itself. I tried to keep it brief and I hope that it can serve a purpose. Let me know if you think that it doesn't work here or should be written differently, etc.
=> Document the internal conversion of string labels to ints/floats and possible edge cases

tests/test_featureset.py, tests/test_utilities.py
This PR addresses the following issues:
- Issue #493: 
- Update several tests in `test_featureset` to add explicit zeros to the`test_feat_dict_list`.
- Update the `check_skll_convert()` function in `test_utilities` to convert features to dense before comparing.
- Issue #497. Remove Python 2.7 from build.
=> Fix Tests using DictVectorizer by Converting to Dense Matrices

conda_requirements.txt
Now that intel has pulled the broken `intel-openmp==2019.5` package from anaconda, we should automatically get the last working version and do not need to pin it in our requirements.
=> Revert Intel OpenMP pinning

skll/learner.py, tests/test_cv.py, tests/utils.py
Addresses #541 . 
- Passes the `Learner` logger down to `FilteredLeaveOneGroupOut` which means any warnings logged by the latter will get printed to the job log.
- Add a new test that triggers said warning which was not being tested before.
=> Add missing logger attribute to `FilteredLeaveOneGroupOut`

doc/run_experiment.rst, doc/utilities.rst, skll/data/readers.py, skll/utilities/filter_features.py, tests/test_featureset.py, tests/test_utilities.py
This PR addresses issue #540. It includes the following updates:
- Modified `CSVReader` and `TSVReader` classes to include an `ignore_blanks` argument, which removes lines that have any `NaN` values, after the `DataFrame` is created. This argument defaults to `False`.
- Modified `CSVReader` and `TSVReader` classes to include a `replace_blanks_with` argument, which replaces any `NaN` values with a new specified value, after the `DataFrame` is created. This argument defaults to `None` (i.e. no replacement). Users can pass either a value or a dictionary of values (if they want to use a difference value for each column).
- Updated the `filter_features.py` utility script to allow users to add the `ignore_blanks` and  `replace_blanks_with` arguments to `CSVReader` and `TSVReader` readers. (Note …
=> Add `ignore_blanks` and `replace_blanks_with` arguments

tests/test_examples.py, tests/test_input.py
For our linux package pre-release testing, we do not activate the environment before running the tests. However, this means that the wrong `python` binary is run when running the dataset creation scripts. This PR fixes that.
It also fixes one other minor issue that seems to be affecting Windows package builds for a different test.
=> Improve testability of `test_examples.py`.

conda-recipe/README.md, conda-recipe/skll/meta.yaml, doc/internal/release.rst, doc/tutorial.rst, skll/version.py
This PR: 
- Updates version number in `version.py`.
- Updates conda recipe and README.
- Updates release process document to include the conda and testpypi tester steps.
- Updates version number in tutorial output in documentation.
To review:
1. Review the changes in the PR.
2. Create a conda environment and test out the conda package with some of your SKLL experiments.
3. Let me know if I missed updating anything in the documentation.
**NOTE**: The pre-release test builds for both [Conda](https://github.com/EducationalTestingService/skll-conda-tester/pull/1) and [TestPyPI](https://github.com/EducationalTestingService/skll-pip-tester/pull/1) pass successfully 🎉.
=> SKLL Release 2.1

skll/learner/__init__.py, tests/test_output.py
This PR closes #572. 
- `Learner.save()` now uses the current working directory if only a filename is specified. 
- Added a test.
=> Allow saving models in current directory without specifying `./`

skll/learner/__init__.py
This PR closes #565. 
- It also modifies the `Learner._create_label_dict()` argument so that it internally keeps track of whether `label_dict` has already been set.
- No additional tests are necessary since the cross-validation and learning curve tests already represent scenarios where this function is called twice, once in the top-level `cross_validate()`/`learning_curve()` methods and once again when the underlying models are trained.
=> Remove `create_label_dict` keyword argument from `Learner.train()`

CONTRIBUTING.md, README.rst, doc/contributing.rst, doc/internal/release.rst, doc/run_experiment.rst
@desilinguist , 
This is in reference to #625 - thanks for raising a very thoughtful issue!
I've followed the [link you shared above](https://medium.com/faun/git-step-by-step-renaming-a-master-branch-to-main-16390ca7577b) and have completed steps 1-4 along with step 9 of updating references to `master` in the code.
Steps 5-8 and 10 on the same link needs to be done on your end (or whoever has the admin privileges to the repo). 
Let me know if there are any other changes you envisioned as part of the `master` > `main` change.
Thanks!
=> words have meaning: renames master branch to main and updates references to master

README.rst, doc/tutorial.rst
One of the last few steps in making `main` the default branch instead of `master`. I have already fixed the integrations in Travis, Azure Pipelines, and ReadTheDocs. Once this is merged, I can delete `master`.
=> Update badges and binder URL

skll/config/utils.py, skll/data/readers.py, skll/experiments/output.py, skll/utils/commandline/generate_predictions.py, tests/test_classification.py, tests/test_examples.py, tests/test_output.py
=> Fix up some cases where open was not done with a context manager, etc.

skll/learner/__init__.py, tests/test_classification.py, tests/test_regression.py
This PR closes #656. 
- Right now, this method basically assumes that all featuresets will be sparse and, hence, [uses](https://github.com/EducationalTestingService/skll/blob/main/skll/learner/__init__.py#L665) the `.data` attribute to get a flattened version of the feature array. However, this does _not_ work for featuresets with dense feature arrays (see the issue for a detailed description of the problem). 
- To handle dense feature arrays, we can use the `.flat` attribute that returns a 1-dimensional iterator over the dense array. 
- Added three new tests: 
- 2 tests that train SKLL models -- one regression & one classification -- with a non-sparse featureset (which would not have worked before this PR) 
- 1 to trigger the other check from this method -- regression with string labels …
=> Fix `Learner._check_input_formatting()` for dense feature sets. 

skll/__init__.py, skll/utils/commandline/print_model_weights.py, tests/other/custom_metrics.txt, tests/other/custom_metrics2.py, tests/test_classification.py, tests/test_custom_metrics.py
This PR closes #661. 
In addition, it makes another minor change of passing in the `beta` argument as a keyword argument since scikit-learn raises a warning otherwise.
=> Remove top-level imports

doc/run_experiment.rst, skll/config/__init__.py, skll/learner/__init__.py, skll/learner/voting.py, tests/configs/test_folds_file.template.cfg, tests/configs/test_folds_file_grid.template.cfg, tests/configs/test_save_cv_folds.template.cfg, tests/configs/test_save_cv_models.template.cfg, tests/test_cv.py, tests/test_voting_learners_api_5.py, tests/test_voting_learners_expts_4.py, tests/utils.py
This PR closes #528. 
- Change default keyword argument values in `Learner.cross_validate()` and `VotingLearner.cross_validate()`.
- Change default value in configuration parser.
- Update tests and test templates to not specify `save_cv_folds` as `True` explicitly but do specify it as `False`.
- Update documentation for this field.
=> Make `save_cv_folds` true by default.

CONTRIBUTING.md, DistributeTests.ps1
This PR closes #677.
- Change "Travis CI" to "Gitlab CI" in CONTRIBUTING.md.
- Change ".travis.yaml" to ".gitlab-ci.yaml" in DistributeTests.ps1.
**Note:** In the issue (and in other parts of the repository), it's spelled "Gitlab," which I defaulted to in order to keep things consistent. However, it's officially spelled "GitLab," [with a capitalized L](https://en.wikipedia.org/wiki/GitLab). We should open another issue to fix this.
=> Replace Travis CI references with Gitlab CI.

MANIFEST.in, setup.py
This PR closes #674.
- Add package_data, exclude_data, and include_package_data methods to setup.py
- Delete MANIFEST.in
**Note:** Tested by running `python setup.py sdist build` once for each setup and running a diff on the generated folders. They were identical!
=> Replace MANIFEST.in with `package_data` in setup.py

skll/config/__init__.py
Addresses issue #647.
- Add line of spacing between docstring parameters.
- Indicate default values after parameter type.
- Add missing period to a single parameter's description.
**Note:** No array parameters found in this file.
=> Rewrite docstrings for skll/config/__init__.py

skll/config/utils.py
- Add space between parameters.
- Remove 'optional' from parameters with default values.
- Move default values next to parameter names.
- Add missing periods to parameter descriptions.
- Add missing double backtick to variable and object names.
- Fix incorrect variable/object reference in _munge_featureset_name docstrings.
- The docstrings reference `feature_set`, which does not exist. The function is passed a variable called `featureset`. The `FeatureSet` object is spelled with camel case.
- As it turns out, `feature_set` was used interchangeably for both the `featureset` variable *and* the `FeatureSet` object.
- `feature_set` reverted to either `featureset` or `FeatureSet`, as appropriate.
- Shortened _munge_featureset_name function description by just a couple words.
**Note:** No array …
=> Rewrite docstrings for skll/config/utils.py

skll/data/dict_vectorizer.py
- Add space between parameters.
- Delete two periods that conflict with the existing style.
- Remove 'optional' from parameters with default values.
- Move default values next to parameter names.
**Notes:** Still no array parameters!
=> Rewrite docstrings for skll/data/dict_vectorizer.py

skll/data/readers.py
- Add space between parameters.
- Change ` to `` when referring to code.
- Remove 'optional' from parameters with default values.
- Move default values next to parameter names.
- Specify shape of arrays and array-likes.
- Update `skll.FeatureSet` and `skll.Reader` to `skll.data.FeatureSet` and `skll.data.Reader`
- Line up variables and text in `replace_blanks_with` parameter descriptions to improve legibility.
**Notes:**
Before the pull request is approved, I'd like to note that both instances of the `replace_blanks_with` parameter include a 'value' option with unspecified type, shown here:
```
replace_blanks_with : value, ``dict``, or ``None``, default=None
```
Later, in the parameter description, it says that this value must be numeric:
```
value   = A (numeric) value with which to …
```
=> Rewrite docstrings for skll/data/readers.py

skll/data/writers.py
- Add space between parameters.
- Remove 'optional' from parameters with default values.
- Move default values next to parameter names.
- Update skll.FeatureSet to skll.data.FeatureSet
=> Rewrite docstrings for skll/data/writers.py

.gitlab-ci.yml, .pre-commit-config.yaml, azure-pipelines.yml, conda-recipe/skll/meta.yaml, conda_requirements.txt, doc/run_experiment.rst, requirements.txt, skll/data/writers.py, skll/learner/__init__.py, skll/learner/utils.py, tests/test_commandline_utils.py, tests/test_featureset.py, tests/test_preprocessing.py, tests/test_regression.py
This PR closes #699. 
This change is pretty straightforward but it’s definitely backwards incompatible which we will reflect in the release version when we put together the release.
The change specifically motivated by the upgrade are:
- Update `requirements.txt` and `conda_requirements.txt` to point to the latest scikit-learn (v1.0.1) and allow up to v1.0.2. 
- Use `squared_error` as the default value of the `loss` parameter for `RANSACRegressor`. 
- Use `toarray()` for converting sparse numpy arrays to dense instead of `todense()` since the latter returns an `np.matrix` instead of an `np.ndarray`. Scikit-learn is planning to drop support for `np.matrix` inputs and is already displaying `FutureWarning`s.
- Force normalize to False for Lars models
-  Scikit-learn v1.0 will be deprecating …
=> Upgrade scikit-learn to v1.0.1

skll/data/readers.py, skll/utils/commandline/filter_features.py, tests/test_commandline_utils.py
This PR closes #693. 
- Raise an exception if `—drop_blanks` removes all rows in the input file if each of them contains a blank value.
- Add a test for this scenario.
- Update `—help` output for `filter_features` to make it clear that `—drop_blanks` and `—replace_blanks_with` only apply to CSV/TSV files.
=> Fix `—drop_blanks` for `filter_features` command line script

doc/tutorial.rst
Added link to SKLL repo in tutorial. This closes #688.
=> Added link to SKLL repo in tutorial

CONTRIBUTING.md, doc/run_experiment.rst
This PR closes #512 and closes #680. 
- Update `CONTRIBUTING.md` file to fix the `git push` instructions (Issue: #512) 
- Add a link to RSMTool’s QWK implementation from the SKLL documentation. We do this _instead of_  moving RSMTool’s QWK implementation to SKLL because that is no longer necessary now that SKLL supports custom metrics. (Issue: #680)
=> Short PR to address 2 minor documentation issues

doc/run_experiment.rst, skll/config/__init__.py, skll/experiments/__init__.py, skll/learner/__init__.py, skll/learner/voting.py, skll/utils/commandline/generate_predictions.py, tests/test_classification.py, tests/test_commandline_utils.py, tests/test_input.py, tests/test_preprocessing.py, tests/test_voting_learners_api_1.py, tests/test_voting_learners_expts_1.py, tests/test_voting_learners_expts_2.py, tests/test_voting_learners_expts_3.py, tests/test_voting_learners_expts_4.py, tests/test_voting_learners_expts_5.py, tests/utils.py
This PR closes #569. 
We are only doing part of the issue here (the renaming) but _not_ moving the `pos_label` field into the `Input` section from the `Tuning` section where it currently lives. This is mainly to minimize the amount of changes that someone would need to go through when converting their old code/config files (renaming can be automated).
=> Rename `pos_label_str` to `pos_label` everywhere.

.gitlab-ci.yml, skll/config/__init__.py, skll/data/readers.py, skll/learner/__init__.py, skll/learner/utils.py, skll/utils/commandline/plot_learning_curves.py
- Use the latest version of codecov report uploader. 
- Install `curl` in the environment since it's needed to get the uploader.
- Typo fixes from last PR that didn't get merged (sorry). 
This PR closes #726.
=> Migrate to new codecov uploader.

.pre-commit-config.yaml, skll/config/__init__.py, skll/config/utils.py, skll/types.py
- Add `mypy` pre-commit check.
- Add type hints to `skll/config/__init.py` and `skll/config/utils.py`.
- Minor code changes to make improve static typing of the code.
- Update docstrings to use the actual type hints. 
This is the first PR in support of #561, with many more to come.
=> Add type hints to `skll.config` module

.pre-commit-config.yaml, skll/config/__init__.py, skll/data/featureset.py, skll/data/readers.py, skll/data/writers.py, skll/types.py, tests/test_featureset.py
1. Update pre-commit checks to include a check for [commit message format](https://www.conventionalcommits.org/en/v1.0.0/#summary) and to exclude missing imports from the `mypy` check. 
2. Add new custom types to `skll.types` module.
3. Add type hints to `skll.data` module
- Refactor code to ensure correct types.
- Add a lot of checks for labels, features, vectorizer being ``None`` that was previously unhandled.
- Update docstrings to use the type hints.
4. Improve type hints in `config/__init__.py`
- Use new `ClassMap` custom type.
- Make sure `pos_label` is typed correctly.
- Fix incorrect default value for sampler parameters.
=> Add type hints to `skll.data` module & improve types in `skll.config` 

CONTRIBUTING.md, skll/data/featureset.py, skll/experiments/utils.py, skll/learner/utils.py, tests/test_featureset.py, tests/test_voting_learners_api_5.py
- Rename method from `split_by_ids` to `split` and edit docstring to explicitly say that the split is done on indices and not id values
- Fix the case where split2 is not specified to use indices and not ids
- Add unittests
This PR closes #727.
=> Bug fix in feature set split method

skll/config/utils.py, skll/experiments/__init__.py, skll/experiments/input.py, skll/experiments/output.py, skll/experiments/utils.py, skll/types.py
- Add new custom types to `skll.types`.
- Fix buggy type hint in `skll.config.utils`.
- Add type hints to all files under `skll.experiments`.
=> Add type hints to `skll.experiments` module

doc/run_experiment.rst, skll/experiments/__init__.py, skll/experiments/utils.py, skll/learner/__init__.py, skll/learner/utils.py, skll/learner/voting.py, skll/types.py, skll/utils/constants.py, tests/test_output.py, tests/test_voting_learners_api_1.py
- Add type hints to `skll.learner`
- Modify `skll.utils.constants` to add type hint.
- Refactor some learner code as needed.
- Add new test and tweak check
- Add new custom types.
- Add type annotations in some places to avoid circular dependencies.
- Fix type in documentation heading
This PR is part of #561.
=> Add type hints to `skll.learner` module + other refactoring

skll/data/featureset.py, skll/data/readers.py, skll/data/writers.py, skll/metrics.py, skll/utils/commandline/compute_eval_from_predictions.py, skll/utils/commandline/filter_features.py, skll/utils/commandline/generate_predictions.py, skll/utils/commandline/join_features.py, skll/utils/commandline/plot_learning_curves.py, skll/utils/commandline/print_model_weights.py, skll/utils/commandline/run_experiment.py, skll/utils/commandline/skll_convert.py, skll/utils/commandline/summarize_results.py, skll/utils/logging.py
- Add type hints to `skll.utils` package.
- Add type hints to `metrics.py` and `logging.py`.
- Add type hints to `skll.data.*` that were missed in previous PRs.
- Refactor some code as necessary.
- Update all docstrings. 
- Ignore some type errors that are redundant. 
This is the last series of type-hinting PRs and will close #561.
=> Add type hints in`skll.utils` module and in all other remaining files. 

.pre-commit-config.yaml, skll/data/readers.py, skll/data/writers.py, skll/experiments/__init__.py, skll/experiments/input.py, skll/experiments/output.py, skll/experiments/utils.py, skll/learner/__init__.py, skll/learner/utils.py, skll/learner/voting.py
- chore: ignore E501 errors in various files. 
- chore: fix docstrings and types in `skll.experiments` and `skll.learner` modules. 
To review this, please look at the [built documentation](https://skll.readthedocs.io/en/647-improve-docstrings-typehints-3/index.html) and check that under "API documentation",  look at the sections "`experiments` Package" and "`learner` Package" and confirm that:
- All parameters have a docstring.
- All type hints have clickable types or type hints.
- The default values are all specified as default = blah.
- All other changes look okay.
This is part of #647.
=> Improve docstrings and type hints (Part 3)

skll/learner/__init__.py, skll/metrics.py, skll/utils/commandline/compute_eval_from_predictions.py, skll/utils/commandline/filter_features.py, skll/utils/commandline/generate_predictions.py, skll/utils/commandline/join_features.py, skll/utils/commandline/plot_learning_curves.py, skll/utils/commandline/print_model_weights.py, skll/utils/commandline/run_experiment.py, skll/utils/commandline/skll_convert.py, skll/utils/commandline/summarize_results.py, skll/utils/logging.py
- chore: ignore E501 errors in various files. 
- chore: fix docstrings and types in `skll.experiments` and `skll.learner` modules. 
To review this, please look at the [built documentation](https://skll.readthedocs.io/en/647-improve-docstrings-typehints-4/index.html) and check that under "API documentation",  look at the sections "`metrics` Package" and "`utils` Package" and confirm that:
- All parameters have a docstring.
- All type hints have clickable types or type hints.
- The default values are all specified as default = blah.
- All other changes look okay.
This is the final PR for #647. Closes #647.
=> Improve docstrings & type hints (Part 4)

doc/run_experiment.rst, skll/learner/__init__.py, skll/utils/constants.py, tests/test_classification.py, tests/test_regression.py
- Add support for HistGradientBoosting learners
- Add imports.
- Add default parameter grids.
- Update documentation:  
- Document default fixed parameters and parameter grids.
- Add the same for Bagging learner that we forgot to do before.
- Also add explicit notes to all learners that require dense features.
- Update ransac regressor note to mention base estimators explicitly.
- Update regression and classification tests. 
Again, best way to to test is to try out the new learners with the California and Iris examples. 
This PR closes #489.
=> Add support for `HistGradientBoostingClassifier` and `HistGradientBoostingRegressor`

CONTRIBUTING.md, README.rst, azure-pipelines.yml, setup.py, skll/learner/utils.py
- Replace deprecated `inspect.getargspec()` in `rescaled` decorator. 
- Switch Azure Pipeline to Python 3.11.
- Add Python 3.11 to `README.rst`, `setup.py`, and `CONTRIBUTING.md`. 
Closes #744.
=> Add support for Python 3.11

doc/custom_metrics.rst, doc/requirements.txt, requirements.txt, skll/__init__.py, skll/data/writers.py, skll/experiments/__init__.py, skll/learner/__init__.py, skll/learner/utils.py, skll/metrics.py, skll/utils/testing.py, tests/test_custom_metrics.py
- Update scikit-learn to v1.3.0.
- Move all custom pre-defined metrics to `_PREDEFINED_CUSTOM_METRICS` dictionary in `metrics.py`.
- Make a copy of the above dictionary as `CUSTOM _METRICS`. This dictionary will be the source of all custom metrics: pre-defined and user-defined.
- We need two dictionaries because at some points in the code, we need to be able to differentiate between pre-defined custom metrics and user-defined custom metrics.
- Remove any use of `sklearn.metrics._scorer` private API and use `sklearn.metrics.get_scorer()` and `sklearn.metrics.get_scorer_names()` instead.
- Use the actual metric function when using custom metrics instead of its name. This is the core change that makes everything work since sklearn validates callables but does not validate custom metric name …
=> Stop using sklearn's private `_scorer` API for custom metrics in SKLL. 

MANIFEST.in, conda-recipe/skll/meta.yaml, doc/contributing.rst, skll/utils/testing.py, skll/version.py, tests/test_input.py
- Update version number.
- Update conda recipe.
- Fix minor issue in testing setup that prevented SKLL Conda Tester and SKLL PyPI tester from working with `nose2`. 
- Update `MANIFEST.in` from including `tests` directory into packages.
- Update `doc/contributing.rst`
- Remove entry for `skll/__init__.py` since it's now blank.
- Update entry for `skll/metrics.py` since it now does more.
- Fix all of the link anchors to point to the correct line numbers.
v4.0 conda and TestPyPI packages have been built, deployed, and tested. 
skll-conda-tester: [passing](https://github.com/EducationalTestingService/skll-conda-tester/pull/8)
skll-pip-tester: [passing](https://github.com/EducationalTestingService/skll-pip-tester/pull/8)
=> Release v4.0.0

conda-recipe/skll/meta.yaml, skll/version.py
Update version number and conda recipe.
v4.0.1 conda and TestPyPI packages have been built, deployed, and tested.
skll-conda-tester: https://github.com/EducationalTestingService/skll-conda-tester/pull/9
skll-pip-tester: https://github.com/EducationalTestingService/skll-pip-tester/pull/9
=> Release v4.0.1

.readthedocs.yml, doc/conf.py, requirements.txt
[Build passes](https://readthedocs.org/projects/skll/builds/) following the fix.
=> Fix ReadTheDocs config

doc/run_experiment.rst, requirements.txt, skll/config/__init__.py, skll/experiments/__init__.py, skll/utils/testing.py, skll/utils/wandb.py, tests/configs/test_wandb.template.cfg, tests/test_input.py, tests/test_output.py, tests/test_wandb.py
This PR adds initial infrastructure for W&B logging, including a configuration field to enable W&B, a wand interface class, documentation and tests.
=> Infrastructure for logging to wandb
