doc/run_experiment.rst

Added some language to the folds file documentation stressing the need for a header line.

Slight modification to folds file documentation

---

skll/data/writers.py
tests/test_output.py

I will next be adding some HTML/Graphic output; however, before doing so adding some tests for the plain text versions.

Adding Report tests

---

skll/learner.py
skll/utilities/print_model_weights.py
tests/test_utilities.py

Stops a crash in learner.py when there is no intercept. 
Stops a crash in print_model_weights.py when the intercept is an array.

Fix some bugs relating to intercept

---

skll/config.py

Fix minor errors that I noticed while going through config.py.

Bugfix/update config.py

---

.travis.yml
skll/learner.py
tests/test_utilities.py

Also added a test for this case.

Fix a bug in print_model_weights for multi class classification

---

.travis.yml

Fixing the `mkl` issue for travis builds.

---

tests/test_classification.py

This is to convince ourselves that the situation in #285 does not happen.

add test for floating point labels in classification

---

skll/learner.py

Add "auto" to the SVR and SVC gamma grids to try and improve performance of the grid search.

add auto to gamma tuning grid for SVR/SVC

---

skll/learner.py
tests/test_utilities.py

Adds in a check for if there is no intercept (it shows up as a bare float of 0.0, compared to a list of floats if an intercept was used). 
Also adds a test.

updating for logistic regression with no intercept

---

.travis.yml
skll/learner.py

Also tweak `.travis.yml` to prevent failed builds for python 3.4 by making sure we install miniconda 3 for python 3.4 builds.

Reshape `coef` to avoid 1D depracation warning in `model_params`

---

conda-recipe/skll/meta.yaml
skll/version.py

SKLL Release 1.5.2

---

doc/conf.py

The years have been updated to 2019 as required.

Years updated

---

.travis.yml
README.rst
conda-recipe/skll/meta.yaml
requirements.txt
requirements_rtd.txt
skll/experiments.py

This PR replaces instances of `prettytable`, which is no longer maintained, with `tabulate`.

Replace prettytable

---

skll/learner.py
tests/test_classification.py
tests/test_regression.py

fixed default parameter duplication for HuberRegressor, MLPClassifier, MLPRegressor

---

doc/run_experiment.rst

Discuss `penalty` parameter for `LogisticRegression`.
Addresses #490

Update documentation for LogisticRegression penalty parameter

---

CONTRIBUTING.md
README.rst

Update contributing guidelines.

---

.travis.yml

This PR removes Python 2.7 version from Travis builds.  It addresses part of #497.

removing Python 2.7 from Travis builds. 

---

.travis.yml

The command `conda update --yes conda` seems to be failing so this PR tries to fix this.

Fix conda bug

---

doc/contributing.rst
doc/tutorial.rst

- Things were broken after we moved files around.

Fix broken links and update code organization section

---

conda-recipe/skll/meta.yaml
conda_requirements.txt
examples/make_titanic_example_data.py
requirements.txt
tests/test_metrics.py

@desilinguist , this closes #630. Will update this PR with local nose test results to double check that there aren't any regressions.

updates scikit to 0.23.2

---

tests/test_ablation.py
tests/test_classification.py
tests/test_custom_learner.py
tests/test_cv.py
tests/test_output.py
tests/test_preprocessing.py
tests/test_regression.py
tests/test_voting_learners_expts_1.py
tests/test_voting_learners_expts_2.py
tests/test_voting_learners_expts_3.py
tests/test_voting_learners_expts_4.py
tests/test_voting_learners_expts_5.py

Add `local=True` to all `run_configuration()` calls in tests.

---

doc/getting_started.rst
doc/tutorial.rst

This PR closes #689 . 
- Add a section on creating environment in tutorial.
- Also add a link for conda on getting started page.

Create environment in tutorial 

---

LICENSE.txt
conda-recipe/skll/meta.yaml
doc/conf.py
skll/version.py

- Update version number and copyright years.
- Conda package has been created and [tested](https://github.com/EducationalTestingService/skll-conda-tester/pull/6).
- TestPyPI package has been  created and [tested](https://github.com/EducationalTestingService/skll-pip-tester/pull/6).

Release v3.1.0

---

.gitlab-ci.yml
.pre-commit-config.yaml
CONTRIBUTING.md
MANIFEST.in
azure-pipelines.yml
conda-recipe/skll/meta.yaml
doc/internal/release.rst
doc/requirements.txt
pyproject.toml
requirements.dev
requirements.txt
skll/version.py

- Update pre-commit checks.
- Update dependencies.
- Remove all dev dependencies from `requirements.txt`.
- Update versions in `doc/requirements.txt`.
- Update version numbers in `version.py` and in the conda recipe.
- Add new `requirements.dev` file. This file contains the runtime as well as dev dependencies.
- Update `CONTRIBUTING.md` to use this file instead of `requirements.txt`.
- Exclude this file in `MANIFEST.in` so that it's not part of the PyPI package.
- Update CI pipelines to use `requirements.dev` instead of `requirements.txt`
- Update release process checklist.
✅ Conda package was created successfully, [uploaded](https://anaconda.org/ets/skll) to anaconda.org, and [tested](https://github.com/EducationalTestingService/skll-conda-tester/pull/11).
✅ PyPI package was created …

v5.0.1 Release
